config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'

  post 'upload_file' => 'home#upload_file', as: :upload_file
  get 'erase_all' => 'home#erase_all', as: :erase_all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabecalho.rb
class Cabecalho < ApplicationRecord
end

app/models/complementonotafiscal.rb
class Complementonotafiscal < ApplicationRecord
end

app/models/consignatario.rb
class Consignatario < ApplicationRecord
end

app/models/dadoscomplementare.rb
class Dadoscomplementare < ApplicationRecord
end

app/models/dadosnotum.rb
class Dadosnotum < ApplicationRecord
end

app/models/dadosredespacho.rb
class Dadosredespacho < ApplicationRecord
end

app/models/destinatario.rb
class Destinatario < ApplicationRecord
end

app/models/intercambio.rb
class Intercambio < ApplicationRecord
end

app/models/localcoletum.rb
class Localcoletum < ApplicationRecord
end

app/models/mercadoria_nota_fiscal.rb
class MercadoriaNotaFiscal < ApplicationRecord
end

app/models/redespacho.rb
class Redespacho < ApplicationRecord
end

app/models/remetente.rb
class Remetente < ApplicationRecord
end

app/models/responsavelfrete.rb
class Responsavelfrete < ApplicationRecord
end

app/models/valorestotaisdocumento.rb
class Valorestotaisdocumento < ApplicationRecord
end

app/models/volumes_nota_fiscal.rb
class VolumesNotaFiscal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require File.expand_path(File.join(Rails.root, "lib", "core.rb"))

class HomeController < ApplicationController
  def index
  end

  def upload_file
    if params[:file].present?
      Item.new(params[:file].read.lines).parse
    end
    redirect_to root_path
  end

  def erase_all
    Intercambio.delete_all
    Cabecalho.delete_all
    Redespacho.delete_all
    Remetente.delete_all
    Localcoletum.delete_all
    Destinatario.delete_all
    Dadosnotum.delete_all
    Complementonotafiscal.delete_all
    Dadoscomplementare.delete_all
    VolumesNotaFiscal.delete_all
    MercadoriaNotaFiscal.delete_all
    Consignatario.delete_all
    Dadosredespacho.delete_all
    Responsavelfrete.delete_all
    Valorestotaisdocumento.delete_all

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row" style="margin-top: 40px;">
  <div class="col-sm-12">
    <div class="box border">
      <div class="box-title">
        <h4>
          <i class="fa fa-file-text-o"></i>
          NF uploader
        </h4>
        <div class="tools"></div>
      </div>
      <div class="box-body">

      <div class="row">
        <div class="col-md-6">
          <%= form_tag :upload_file, multipart: true do %>
            <div class="control-label">
              <span class='label label-info' id="upload-file-info"></span><br />
              <label class="btn btn-default btn-file">
                Browse <%= file_field_tag :file, class: 'form-control', style: 'display:none', onchange: "$('#upload-file-info').html($(this).val());" %>
              </label>
            </div>

            <div class="control-label">
              <%= submit_tag :enviar, class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="col-md-6">
        <%= link_to 'APAGAR TODOS OS REGISTROS', erase_all_path, class: 'btn btn-danger' %>
        </div>
      </div>

      <div class="1">
        <% if Intercambio.any? %>
          <h4>Intercambio</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>Remetente</th>
                <th>Destinatario</th>
              </tr>
            </thead>
            <tbody>
              <% Intercambio.all.each do |i| %>
                <tr>
                  <td><%= i.remetente %></td>
                  <td><%= i.destinatario %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if Cabecalho.any? %>
          <h4>Cabeçalho</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>Identificação do Documento</th>
              </tr>
            </thead>
            <tbody>
              <% Cabecalho.all.each do |i| %>
                <tr>
                  <td><%= i.indentificacao_documento %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if Redespacho.any? %>
          <h4>Redespacho</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>Identificação do Documento</th>
                <th>cnpj_emissio</th>
                <th>sigla_fiscal</th>
                <th>numero</th>
                <th>serie</th>
                <th>total_frete</th>
                <th>frete_peso</th>
                <th>frete_valor</th>
              </tr>
            </thead>
            <tbody>
              <% Redespacho.all.each do |i| %>
                <tr>
                  <td><%= i.cnpj_emissio %></td>
                  <td><%= i.sigla_fiscal %></td>
                  <td><%= i.numero %></td>
                  <td><%= i.serie %></td>
                  <td><%= i.total_frete %></td>
                  <td><%= i.frete_peso %></td>
                  <td><%= i.frete_valor %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if Remetente.any? %>
          <h4>Remetente</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>cnpj</th>
                <th>inscricao_estadual</th>
                <th>endereco</th>
                <th>cidade</th>
                <th>cep</th>
                <th>uf</th>
                <th>razao_social</th>
              </tr>
            </thead>
            <tbody>
              <% Remetente.all.each do |i| %>
                <tr>
                  <td><%= i.cnpj %></td>
                  <td><%= i.inscricao_estadual %></td>
                  <td><%= i.endereco %></td>
                  <td><%= i.cidade %></td>
                  <td><%= i.cep %></td>
                  <td><%= i.uf %></td>
                  <td><%= i.razao_social %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if Localcoletum.any? %>
          <h4>Local Coleta</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>cnpj</th>
                <th>razao_social</th>
                <th>inscricao_estadual</th>
                <th>endereco_solicitante</th>
                <th>complemento_endereco</th>
                <th>bairro</th>
                <th>cidade</th>
                <th>uf</th>
                <th>pais</th>
                <th>cep</th>
                <th>telefone_fixo</th>
              </tr>
            </thead>
            <tbody>
              <% Localcoletum.all.each do |i| %>
                <tr>
                  <td><%= i.cnpj %></td>
                  <td><%= i.razao_social %></td>
                  <td><%= i.inscricao_estadual %></td>
                  <td><%= i.endereco_solicitante %></td>
                  <td><%= i.complemento_endereco %></td>
                  <td><%= i.bairro %></td>
                  <td><%= i.cidade %></td>
                  <td><%= i.uf %></td>
                  <td><%= i.pais %></td>
                  <td><%= i.cep %></td>
                  <td><%= i.telefone_fixo %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if Destinatario.any? %>
          <h4>Destinatario</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>razao_social</th>
                <th>cnpj</th>
                <th>inscricao_estadual</th>
                <th>endereco</th>
                <th>bairro</th>
                <th>cidade</th>
                <th>cep</th>
                <th>codigo_municipio</th>
                <th>uf</th>
                <th>area_frete</th>
                <th>numero_comunicacao</th>
              </tr>
            </thead>
            <tbody>
              <% Destinatario.all.each do |i| %>
                <tr>
                  <td><%= i.razao_social %></td>
                  <td><%= i.cnpj %></td>
                  <td><%= i.inscricao_estadual %></td>
                  <td><%= i.endereco %></td>
                  <td><%= i.bairro %></td>
                  <td><%= i.cidade %></td>
                  <td><%= i.cep %></td>
                  <td><%= i.codigo_municipio %></td>
                  <td><%= i.uf %></td>
                  <td><%= i.area_frete %></td>
                  <td><%= i.numero_comunicacao %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>


        <% if Dadosnotum.any? %>
          <h4>Dados Nota</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>romaneio_coleta</th>
                <th>cod_rota</th>
                <th>condicao_frete</th>
                <th>serie</th>
                <th>numero</th>
                <th>natureza_mercadoria</th>
                <th>especie_acionamento</th>
                <th>volume</th>
                <th>valor_mercadoria</th>
                <th>peso_total</th>
                <th>peso_densidade_cubagem</th>
              </tr>
            </thead>
            <tbody>
              <% Dadosnotum.all.each do |i| %>
                <tr>
                  <td><%= i.romaneio_coleta %></td>
                  <td><%= i.cod_rota %></td>
                  <td><%= i.condicao_frete %></td>
                  <td><%= i.serie %></td>
                  <td><%= i.numero %></td>
                  <td><%= i.natureza_mercadoria %></td>
                  <td><%= i.especie_acionamento %></td>
                  <td><%= i.volume %></td>
                  <td><%= i.valor_mercadoria %></td>
                  <td><%= i.peso_total %></td>
                  <td><%= i.peso_densidade_cubagem %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if MercadoriaNotaFiscal.any? %>
          <h4>Mercadoria Nota Fiscal</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>quantidade_volumes</th>
                <th>especie_acionamento</th>
                <th>mercadoria_nota_fiscal</th>
                <th>quantidade_volumes2</th>
                <th>especie_acionamento2</th>
                <th>mercadoria_nota_fiscal2</th>
                <th>quantidade_volumes3</th>
                <th>especie_acionamento3</th>
                <th>mercadoria_nota_fiscal3</th>
                <th>quantidade_volumes4</th>
                <th>especie_acionamento4</th>
                <th>mercadoria_nota_fiscal4</th>
              </tr>
            </thead>
            <tbody>
              <% MercadoriaNotaFiscal.all.each do |i| %>
                <tr>
                  <td><%= i.quantidade_volumes %></td>
                  <td><%= i.especie_acionamento %></td>
                  <td><%= i.mercadoria_nota_fiscal %></td>
                  <td><%= i.quantidade_volumes2 %></td>
                  <td><%= i.especie_acionamento2 %></td>
                  <td><%= i.mercadoria_nota_fiscal2 %></td>
                  <td><%= i.quantidade_volumes3 %></td>
                  <td><%= i.especie_acionamento3 %></td>
                  <td><%= i.mercadoria_nota_fiscal3 %></td>
                  <td><%= i.quantidade_volumes4 %></td>
                  <td><%= i.especie_acionamento4 %></td>
                  <td><%= i.mercadoria_nota_fiscal4 %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <% if Valorestotaisdocumento.any? %>
          <h4>VALORES TOTAIS DO DOCUMENTO</h4>
          <table class="table table-striped table-responsive">
            <thead class="header">
              <tr>
                <th>valor_total_notas</th>
                <th>peso_total_notas</th>
                <th>peso_total_densidade_cubagem</th>
                <th>quantitade_total_volumes</th>
                <th>valor_total_cobrado</th>
                <th>valor_total_seguro</th>
              </tr>
            </thead>
            <tbody>
              <% Valorestotaisdocumento.all.each do |i| %>
                <tr>
                  <td><%= i.valor_total_notas %></td>
                  <td><%= i.peso_total_notas %></td>
                  <td><%= i.peso_total_densidade_cubagem %></td>
                  <td><%= i.quantitade_total_volumes %></td>
                  <td><%= i.valor_total_cobrado %></td>
                  <td><%= i.valor_total_seguro %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdvWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="pdv-bg">
          <h1><%= image_tag 'pdv.png' %>&nbsp;&nbsp;<i class="fa fa-bicycle fa-fw"></i></h1>
          <p>Rede Ciclologística.</p>
        </div>
        <%= yield %>
      </div>
    </div>
    </div>
  </body>
</html>